name: CI
env:
    DEBUG: napi:*
    APP_NAME: files-rs
    MACOSX_DEPLOYMENT_TARGET: '10.13'
permissions:
    contents: write
    id-token: write
'on':
    push:
        branches:
            - master
        tags-ignore:
            - '**'
        paths-ignore:
            - '**/*.md'
            - '**/LICENSE'
            - '**/*.gitignore'
            - '**/*.editorconfig'
    pull_request: null
defaults:
    run:
        shell: bash
jobs:
    Test:
        name: Test ${{ matrix.settings.target }}-node@${{ matrix.node }}
        strategy:
            fail-fast: false
            matrix:
                settings:
                  - host: ubuntu-latest
                    os: ubuntu
                    version: latest
                    target: x86_64-unknown-linux-gnu
                    lib: gnu
                    architecture: x64
                node:
                    - 20
        runs-on: ${{ matrix.settings.host }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4.2.1
          - name: Install node
            uses: actions/setup-node@v4
            with:
                node-version: ${{ matrix.node }}
          - name: Check node
            run: |
                node -v
                npm -v
                node -p "process.platform"
                node -p "process.arch"
          - name: Check yarn
            run: yarn -v
          - name: Install Bun
            uses: oven-sh/setup-bun@v2.0.1
          - name: Check Bun
            run: |
                bun -v
                bun -e "console.log(process.platform)"
                bun -e "console.log(process.arch)"
          - name: Install dependencies
            run: bun i --no-save
          - name: Build
            run: bun run build
          - name: Upload dist artifact
            uses: actions/upload-artifact@v4
            with:
                name: bindings-dist
                path: "dist/**/*"
                if-no-files-found: error
          - name: Bun test
            run: bun test
    Publish:
        name: Publish
        needs:
            - Test
        strategy:
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4.2.1
          - name: Install node
            uses: actions/setup-node@v4
            with:
                node-version: 20
                registry-url: 'https://registry.npmjs.org'
          - name: Check node
            run: |
                node -v
                npm -v
                node -p "process.platform"
                node -p "process.arch"
          - name: Check yarn
            run: yarn -v
          - name: Install Bun
            uses: oven-sh/setup-bun@v2.0.1
          - name: Check Bun
            run: |
                bun -v
                bun -e "console.log(process.platform)"
                bun -e "console.log(process.arch)"
          - name: Install dependencies
            run: bun i --no-save
          - name: Download dist artifacts
            uses: actions/download-artifact@v4
            with:
                name: bindings-dist
                path: 'dist'
          - name: Publish package in npm
            run: bun publish
            env:
                BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          - name: Publish package in jsr
            run: bunx -b jsr publish
